# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- script: | 
    dotnet restore OnLoanApprovedByCreditor.sln
    ls
  displayName: 'dotnet restore'


- script: | 
    dotnet build OnLoanApprovedByCreditor.sln
    ls
    cd /home/vsts/work/1/s/OnLoanApprovedByCreditor/bin/Debug/netcoreapp2.1/
    ls -al
    pwd
  displayName: 'dotnet build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '/home/vsts/work/1/s/OnLoanApprovedByCreditor/bin/Debug/netcoreapp2.1/'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    
- task: LambdaNETCoreDeploy@1
  inputs:
    awsCredentials: 'awsconnection'
    regionName: 'ap-south-1'
    command: 'deployFunction'
    packageOnly: false
    lambdaProjectPath: './OnLoanApprovedByCreditor'
    functionName: 'OnLoanApprovedByCreditor'
    functionRole: 'cloudform-LambdaExecutionRole-1XRKE2AES4R75'
    functionHandler: 'OnLoanApprovedByCreditor::OnLoanApprovedByCreditor.Function::FunctionHandler'
    functionMemory: 512
    functionTimeout: 3

- task: AWSCLI@1
  inputs:
    awsCredentials: 'awsconnection'
    regionName: 'ap-south-1'
    awsCommand: 'lambda'
    awsSubCommand: 'update-function-configuration'
    awsArguments: '--function-name OnLoanApprovedByCreditor --environment "Variables={LoanApprovalURL=https://vdub1eldd6.execute-api.ap-south-1.amazonaws.com/v1/loanapproval/banker}"'