# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- script: | 
    dotnet restore OnLoanApprovedByCreditor.sln
    ls
  displayName: 'dotnet restore'


- script: | 
    dotnet build OnLoanApprovedByCreditor.sln
    ls
    cd /home/vsts/work/1/s/OnLoanApprovedByCreditor/bin/Debug/netcoreapp2.1/
    ls -al
    pwd
  displayName: 'dotnet build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '/home/vsts/work/1/s/OnLoanApprovedByCreditor/bin/Debug/netcoreapp2.1/'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    
- task: LambdaDeployFunction@1
  inputs:
    awsCredentials: 'awsconnection'
    regionName: 'ap-south-1'
    deploymentMode: 'codeandconfiguration'
    functionName: 'OnLoanApprovedByCreditor'
    functionHandler: 'OnLoanApprovedByCreditor::OnLoanApprovedByCreditor.Function::FunctionHandler'
    runtime: 'dotnetcore2.1'
    codeLocation: 'localfile'
    localZipFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    roleARN: 'cloudform-LambdaExecutionRole-1XRKE2AES4R75'
    environment: |
      LoanApprovalURL=https://g9yh14f7ve.execute-api.ap-south-1.amazonaws.com/Authorizeddev/loanapproval/banker
